spring:
  kafka:
    producer:
      batch-size: 0
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
    properties:
      schema.registry.url: http://localhost:8081
    bootstrap-servers: localhost:19092,localhost:29092,localhost:39092

kafka:
  topic:
    view: view
    click: click